tasks:
  - name: Setup Flutter
    init: |
      git clone https://github.com/flutter/flutter.git -b stable
      echo 'export PATH="$PATH:/workspace/mamu_flutter_app/flutter/bin"' >> ~/.bashrc
      export PATH="$PATH:/workspace/mamu_flutter_app/flutter/bin"
      flutter --version
      flutter pub get
    command: |
      flutter doctor

vscode:
  extensions:
    - Dart-Code.flutter
    - Dart-Code.dart-code
